eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://RESTAURANT-SERVICE/restaurant/orders/status/
